requires 'Carp';
requires 'Socket';
requires 'Readonly';
requires 'Net::Domain';
requires 'URI::Escape';
requires 'XML::LibXML';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'HTTP::Request::Common';